version: "3.8"
name: base

services:
    proxy:
        container_name: almx-lab-nginx-proxy-server
        image: nginx:latest
        restart: unless-stopped
        environment:
            SERVER_DOMAIN: alemax.dev.br
            SERVER_LOCAL_IP: 192.168.0.144
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src/nginx/templates:/etc/nginx/templates
            - ./src/nginx/log.conf:/etc/nginx/log.conf
            - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    portainer:
        container_name: almx-lab-portainer
        image: portainer/portainer-ce:latest
        ports:
            - 9443:9443
        volumes:
            - /media/archive/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
    cloudflare-ddns:
      container_name: almx-lab-cloudflare-ddns
      image: favonia/cloudflare-ddns:latest
      network_mode: host
      restart: always
      user: "1000:1000"
      read_only: true
      cap_drop: [all]
      environment:
        - CLOUDFLARE_API_TOKEN=B63UBbfEpeym9Ka33-5eEbcrBaQnjo96IoSEsQ7F
        - DOMAINS=alemax.dev.br,jellyfin.alemax.dev.br,retrom.alemax.dev.br,pokedex.alemax.dev.br,docker.alemax.dev.br
        - PROXIED=true
    retrom:
      container_name: almx-lab-retrom
      image: ghcr.io/jmberesford/retrom-service:latest
      ports:
        - 5101:5101
        - 4444:3000
      volumes:
        - /media/archive/retrom/library:/app/library
        - /media/archive/retrom/config:/app/config/
        - /media/archive/retrom/data:/app/data/
    gitea:
        image: docker.io/gitea/gitea:1.23.1
        container_name: almx-lab-gitea
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - GITEA__database__DB_TYPE=postgres
            - GITEA__database__HOST=postgres:5432
            - GITEA__database__NAME=gitea
            - GITEA__database__USER=postgres
            - GITEA__database__PASSWD=postgres
        restart: always
        volumes:
            - /media/archive/gitea:/data
            - ./src/gitea/app.ini:/data/conf/app.ini
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3040:3000
            - 222:22
        depends_on:
            - postgres
    syncthing:
      image: syncthing/syncthing
      container_name: almx-lab-syncthing
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - /media/archive/syncthing:/var/syncthing
      ports:
        - 8384:8384 # Web UI
        - 22000:22000/tcp # TCP file transfers
        - 22000:22000/udp # QUIC file transfers
        - 21027:21027/udp # Receive local discovery broadcasts
      restart: unless-stopped
      healthcheck:
        test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
        interval: 1m
        timeout: 10s
        retries: 3
    samba:
        container_name: almx-lab-samba
        image: crazymax/samba
        network_mode: host
        volumes:
            - ./samba:/data
            - /media/archive/:/samba/archive
        environment:
            - "BROWSABLE=yes"
        restart: always
    gitearunner:
      image: gitea/act_runner
      container_name: almx-lab-gitea-runner
      restart: always
      depends_on:
        - gitea
      volumes:
        - /media/archive/gitearunner:/data
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - GITEA_INSTANCE_URL=https://gitea.alemax.dev.br
        - GITEA_RUNNER_REGISTRATION_TOKEN=8lEv1dpRBtHuRMd3RJjLfyEhO7btRKYi0dbvUijs
    affine:
        image: ghcr.io/toeverything/affine-graphql:stable
        container_name: almx-lab-affine
        ports:
            - '3010:3010'
        depends_on:
            - redis
            - postgres
            - affine_migration
        volumes:
            # custom configurations
            - /media/archive/affine/self-host/storage:/root/.affine/storage
            - /media/archive/affine/self-host/config:/root/.affine/config
        environment:
            - AFFINE_SERVER_EXTERNAL_URL=https://affine.alemax.dev.br
            - REDIS_SERVER_HOST=redis
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/affine
        restart: unless-stopped
    affine_migration:
        image: ghcr.io/toeverything/affine-graphql:stable
        container_name: affine_migration_job
        volumes:
            - /media/archive/affine/self-host/storage:/root/.affine/storage
            - /media/archive/affine/self-host/config:/root/.affine/config
        command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
        environment:
            - AFFINE_SERVER_EXTERNAL_URL=https://affine.alemax.dev.br
            - REDIS_SERVER_HOST=redis
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/affine
        depends_on:
            - postgres
            - redis
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: almx-lab-jellyfin
        group_add:
            - "993" 
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /media/archive/jellyfin/library:/config
            - /media/archive/jellyfin/tvseries:/data/tvshows
            - /media/archive/jellyfin/movies:/data/movies
            - /media/archive/jellyfin/music:/data/music
            - /media/archive/jellyfin/plugins:/data/plugins
        devices:
            - /dev/dri/renderD128:/dev/dri/renderD128
        ports:
            - 8096:8096
            - 8920:8920
            - 7359:7359/udp
            - 1900:1900/udp
        restart: unless-stopped
    rdtclient:
        image: rogerfar/rdtclient
        container_name: almx-lab-rdtclient
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /media/archive/rdt/db:/data/db
            - /media/archive/rdt/downloads:/data/downloads
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 6500:6500
        restart: unless-stopped
    scrobbler:
        image: foxxmd/multi-scrobbler
        container_name: almx-lab-scrobbler
        environment:
            - TZ=America/Fortaleza
            #- SPOTIFY_CLIENT_ID=
            #- SPOTIFY_CLIENT_SECRET=
            #- SPOTIFY_REDIRECT_URI=http://multi-scrobbler-host-IP:9078/callback ## Need to be whitelisted in Spotify dashboard and is used for creating the connection first time
            - MALOJA_URL=https://maloja.alemax.dev.br
            - MALOJA_API_KEY=FiddtQJIBHgh4541DMCqmnkttcljIoZX1UWSO7rfc5UXKG5Uy1DrpZP9n7TM8MNI
            - PUID=1000
            - PGID=1000
            - BASE_URL=https://scrobbler.alemax.dev.br
        volumes:
            - /media/archive/scrobbler/config:/config
            - ./src/scrobbler/config/config.json:/config/config.json
        ports:
            - 9078:9078
        restart: unless-stopped
    maloja:
        image: krateng/maloja
        container_name: almx-lab-maloja
        environment:
            MALOJA_SKIP_SETUP: true
            MALOJA_DATA_DIRECTORY: /mljdata
            PUID: 1000
            PGID: 1000
        volumes:
            - /media/archive/mljdata:/mljdata
        ports:
            - 42010:42010
        restart: unless-stopped
    kavita:
        container_name: almx-lab-kavita
        image: jvmilazz0/kavita:latest
        ports:
            - 5000:5000
        volumes:
            - /media/archive/mangas:/manga
            - /media/archive/kavita:/kavita/config
        environment:
            - TZ=America/Sao_Paulo
            - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
        restart: unless-stopped
    filebrowser:
        container_name: almx-lab-filebrowser
        image: hurlenko/filebrowser
        user: "1000:1000"
        ports:
            - 4430:8080
        volumes:
            - /media/archive:/data
            - /media/archive/filebrowser:/config
        environment:
            - FB_BASEURL=/filebrowser
        restart: always
    qbittorrent:
        container_name: almx-lab-qbittorrent
        image: linuxserver/qbittorrent:latest
        restart: unless-stopped
        environment:
            - TZ=America/Sao_Paulo
        ports:
            - 8090:8080
            - 6881:6881/tcp
            - 6881:6881/udp
        volumes:
            - /media/archive/torrents/config:/config
            - /media/archive/torrents/data:/data
            - /media/archive/torrents/downloads:/downloads:rw
            - /media/archive/torrents/incomplete:/incomplete
    ghost:
        container_name: almx-lab-ghost
        image: ghost:5-alpine
        restart: always
        user: "1000:1000"
        ports:
            - 2368:2368
        environment:
            database__client: mysql
            database__connection__host: mysql
            database__connection__user: root
            database__connection__password: mysql
            database__connection__database: ghostmanysoba
            url: https://ghost.alemax.dev.br
        volumes:
            - /media/archive/ghost-manysoba:/var/lib/ghost/content
    mysql:
        container_name: almx-lab-mysql
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        volumes:
            - /media/archive/mysql/db:/var/lib/mysql
    redis:
        image: redis
        container_name: almx-lab-redis
        healthcheck:
            test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
    postgres:
        image: docker.io/library/postgres:14
        container_name: almx-lab-postgres-db
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - /media/archive/postgres-db:/var/lib/postgresql/data
            - ./src/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql