name: base

include:
    - ./services/infra/cloudflare-ddns.yml
    - ./services/infra/portainer.yml
    - ./services/infra/samba.yml
    - ./services/apps/qbittorrent.yml
    - ./services/infra/nginx.yml
    - ./services/infra/syncthing.yml
    - ./services/infra/postgres.yml
    - ./services/media/jellyfin.yml
    - ./services/apps/rdtclient.yml
    - ./services/infra/filebrowser.yml
    - ./apps/remotes/cfnview/.homelab/service.yml
