name: base

services:
    ps3netsrv:
        container_name: ${PREFIX}-ps3netsrv
        image: shawly/ps3netsrv:latest
        restart: unless-stopped
        environment:
            - USER_ID=1000
            - GROUP_ID=1000
            - TZ=America/Sao_Paulo
        ports:
            - 38008:38008
        volumes:
            - ${STORAGE}/Games/ps3/isos:/games/PS3ISO
