name: base

services:
    github-mcp:
        container_name: ${PREFIX}-github-mcp
        image: ghcr.io/github/github-mcp-server:latest
        restart: unless-stopped
        command: ["--transport=sse"]
        environment:
            - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
        ports:
            - 8085:8080
