name: base

services:
    homeassistant:
        image: ghcr.io/home-assistant/home-assistant:stable
        container_name: ${PREFIX}-homeassistant
        environment:
            - TZ=America/Sao_Paulo
        volumes:
            - ${STORAGE}/homeassistant/config:/config
            - ./homeassistant/configuration.yaml:/config/configuration.yaml:ro
        network_mode: host
        restart: unless-stopped
