name: base

services:
    obs:
        image: alexanderwagnerdev/obs:latest
        container_name: ${PREFIX}-obs
        shm_size: "8gb"
        environment:
            - VNC_PASS=${OBS_VNC_PASS}
            - TZ=America/Sao_Paulo
        devices:
            - /dev/video0:/dev/video0
            - /dev/snd:/dev/snd
        ports:
            - 6080:6080
            - 5900:5900
        restart: unless-stopped
